#   Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved
#
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# APIM Configuration Parameters
com.rukspot.restclient:
  # hostname
  dcrEndpoint: https://localhost:9443/client-registration/v0.17/register
  # hostname
  publisherEndpoint: https://localhost:9443/api/am/publisher/v1
  # hostname
  devPortalEndpoint: https://localhost:9443/api/am/store/v1
  # hostname
  adminEndpoint: https://localhost:9443/api/am/admin/v0.17
  # hostname
  tokenEndpoint: https://localhost:9443/oauth2/token
  # hostname
  adminServiceBaseUrl: https://localhost:9443
  # hostname
  gwEndpoint: https://localhost:8243
  # hostname
  wsEndpoint: ws://localhost:9099
  # hostname
  amHome: /Users/rukshan/wso2/apim/3.2.0/testing/target/mysql/wso2am-3.2.0-SNAPSHOT
  # hostname
  appThrottlePolicy: 1PerMin
  # hostname
  defaultThrottlePolicy: 50PerMin
  # hostname
  defaultPass: admin
    # API developer scopes
  apiDeveloperScopes: apim:api_view apim:api_create apim:api_publish apim:api_delete
  # APP developer scopes
  appDeveloperScopes: apim:subscribe apim:app_manage apim:sub_manage
  # APP developer scopes
  adminScopes: apim:tier_manage apim:tier_view
    # APP developer scopes
  testCases:
#  -
#    apiName: sample
#    apiType: rest
#    creator: admin
#    initVersion: 1.0.0
#    publisher: admin
#    subscriptions:
#    - appName: sample
#      appPolicy: Unlimited
#      subscriber: admin
#      users:
#      - admin
#    supportOperations:
#    - method: GET
#      template: /menu
#    testOperations:
#    - delay: 0
#      method: GET
#      payload: null
#      template: /menu
#      times: 1
#    version:
#    - 2.0.0
#    - 3.0.0
  -
    apiName: default
    endpoint: https://localhost:9443/am/sample/pizzashack/v1/api/
    apiType: rest
    creator: pub1
    initVersion: 1.0.0
    publisher: pub1
    subscriptions:
      - appName: default
        appPolicy: Unlimited
        subscriber: sub1
        users:
          - user1
          - user2
    supportOperations:
      - method: GET
        template: /menu
    testOperations:
      - delay: 0
        method: GET
        payload: null
        template: /menu
        times: 1
    version:
      - 1.1.0
      - 1.2.0

  -
    apiName: throttled
    endpoint: https://localhost:9443/am/sample/pizzashack/v1/api/
    apiType: rest
    creator: pub2
    initVersion: 1.0.0
    publisher: pub1
    subscriptions:
      - appName: throttled
        appPolicy: 1PerMin
        subscriber: sub2
        users:
          - user2
          - user3
    supportOperations:
      - method: GET
        template: /menu
    testOperations:
      - delay: 2
        method: GET
        payload: null
        template: /menu
        times: 2
    version:
      - 1.1.0
      - 1.2.0

  -
    apiName: noAuth
    endpoint: https://localhost:9443/am/sample/pizzashack/v1/api/
    apiType: rest
    creator: pub3
    initVersion: 2.0.0
    publisher: pub3
    subscriptions:
      - appName: noNeed
        appPolicy: 1PerMin
        subscriber: sub2
        users:
          - user2
          - user3
    supportOperations:
      - method: GET
        template: /menu
        security: false
    testOperations:
      - delay: 0
        method: GET
        payload: null
        template: /menu
        times: 2
        security: false
    version:
      - 2.1.0
      - 2.2.0

  -
    apiName: faulty
    endpoint: https://localhost:9543/am/sample/pizzashack/v1/api/
    apiType: rest
    creator: pub1
    initVersion: 3.0.0
    publisher: pub1
    subscriptions:
      - appName: faulty
        appPolicy: Unlimited
        subscriber: sub3
        users:
          - user2
          - user3
    supportOperations:
      - method: GET
        template: /menu
    testOperations:
      - delay: 0
        method: GET
        payload: null
        template: /menu
        times: 1
    version:
      - 3.1.0
      - 3.2.0

  -
    apiName: code_api
    endpoint: http://localhost:9090/inventory/customers/
    apiType: rest
    creator: pub2
    initVersion: 4.0.0
    publisher: pub2
    subscriptions:
      - appName: code_app
        appPolicy: Unlimited
        subscriber: admin
        users:
          - user1
          - user3
    supportOperations:
      - method: GET
        template: /{code}
    testOperations:
      - delay: 0
        method: GET
        payload: null
        template: /201
        times: 2
      - delay: 0
        method: GET
        payload: null
        template: /408
        times: 2
      - delay: 0
        method: GET
        payload: null
        template: /501
        times: 10
    version:
      - 4.1.0
      - 4.2.0

  -
    apiName: graphql
    endpoint: https://api.graph.cool/simple/v1/swapi
    apiType: graphql
    creator: pub2
    initVersion: 5.0.0
    publisher: pub2
    subscriptions:
      - appName: graphql
        appPolicy: Unlimited
        subscriber: sub2
        users:
          - user1
          - user2
    testOperations:
      - delay: 0
        method: POST
        payload: '{"query":"{\n  allAssets {\n    id\n  }\n  allFilms {\n    id\n  }\n}\n"}'
        template: /
        times: 1
    version:
      - 5.1.0
      - 5.2.0

  -
    apiName: websocket
    endpoint: ws://localhost:7474/
    apiType: websocket
    creator: pub3
    initVersion: 6.0.0
    publisher: pub3
    subscriptions:
      - appName: websocket
        appPolicy: Unlimited
        subscriber: sub3
        users:
          - user2
          - user3
    testOperations:
      - delay: 0
        method: POST
        payload: '{message:"hello response from web socket test api"}'
        template: /
        times: 1
    version:
      - 6.1.0
      - 6.2.0

  -
    apiName: soapPass
    endpoint: https://localhost:9443/services/UserProfileMgtService
    apiType: soap
    creator: pub1
    initVersion: 7.0.0
    publisher: pub1
    subscriptions:
      - appName: soapPass
        appPolicy: Unlimited
        subscriber: sub1
        users:
          - user3
          - user1
    testOperations:
      - delay: 0
        method: POST
        payload: '<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:mgt="http://mgt.profile.user.identity.carbon.wso2.org">
                     <soap:Header/>
                     <soap:Body>
                        <mgt:getUserProfile>
                           <mgt:username>admin</mgt:username>
                           <mgt:profileName>default</mgt:profileName>
                        </mgt:getUserProfile>
                     </soap:Body>
                  </soap:Envelope>'
        template: /
        times: 1
        headers:
          SOAPAction: urn:getUserProfile
          Content-Type: application/soap+xml
    version:
      - 7.1.0
      - 7.2.0

  -
    apiName: SimpleProduct
    apiType: product
    creator: pub1
    publisher: pub1
    subscriptions:
      - appName: SimpleProduct
        appPolicy: Unlimited
        subscriber: sub1
        users:
          - user1
          - user2
    apiResources:
      - apiName: default
        version: 1.0.0
        operations:
          -
            method: GET
            security: true
            template: /menu
      - apiName: code_api
        version: 4.0.0
        operations:
          -
            method: GET
            security: true
            template: /{code}
    testOperations:
      - delay: 0
        method: GET
        template: /menu
        times: 1
      - delay: 0
        method: GET
        template: /201
        times: 1
      - delay: 0
        method: GET
        template: /401
        times: 1
      - delay: 0
        method: GET
        template: /501
        times: 2

  testConfigs:
    tenants:
    - carbon.super
#    - wso2.com
    throttlePolicy:
    - count: 1
      name: 1PerMin
      type: Application
    users:
    - username: pub1
      roles:
      - Internal/publisher
      - Internal/creator
    - username: pub2
      roles:
        - Internal/publisher
        - Internal/creator
    - username: pub3
      roles:
        - Internal/publisher
        - Internal/creator
    - username: sub1
      roles:
        - Internal/subscriber
    - username: sub2
      roles:
        - Internal/subscriber
    - username: sub3
      roles:
        - Internal/subscriber
    - username: user1
      roles:
        - Internal/everyone
    - username: user2
      roles:
        - Internal/everyone
    - username: user3
      roles:
        - Internal/everyone
    - username: manager
      roles:
        - Internal/analytics
